- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - build-essential
    - automake
    - fuse
    - libfuse-dev
    - libcurl4-openssl-dev
    - libxml2-dev
    - libssl-dev

- name: clone source code
  git:
    repo: https://github.com/s3fs-fuse/s3fs-fuse.git
    version: "{{ s3fs_version }}"
    dest: /usr/local/src/s3fs-fuse
    accept_hostkey: yes

- name: install s3fs
  command: "{{ item }}"
  args:
    chdir: /usr/local/src/s3fs-fuse
    creates: "{{ s3fs_install_dir }}/bin/s3fs"
  with_items:
    - "./autogen.sh"
    - "./configure --prefix={{ s3fs_install_dir }}"
    - "make"
    - "make install"
